server:
  port: 3031

spring:
  application:
    name: auth-service

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8282/realms/learning-platform
      client:
        registration:
          keycloak:
            client-id: auth-service
            client-secret: rDVFyUJzUTPt6D6DBFVgmAK8UaEuPDpv
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - openid
              - profile
              - email
        provider:
          keycloak:
            issuer-uri: http://localhost:8282/realms/learning-platform
            authorization-uri: http://localhost:8282/realms/learning-platform/protocol/openid-connect/auth
            token-uri: http://localhost:8282/realms/learning-platform/protocol/openid-connect/token
            user-info-uri: http://localhost:8282/realms/learning-platform/protocol/openid-connect/userinfo
            jwk-set-uri: http://localhost:8282/realms/learning-platform/protocol/openid-connect/certs
            user-name-attribute: preferred_username

  main:
    allow-bean-definition-overriding: true

  servlet:
    context-path: /auth

  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false

logging:
  level:
    org.springframework.security: DEBUG
